"""catalog billing v2 foundation
Revision ID: b41c9d2e7f60
Revises: a27d5c9e41f0
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import uuid, json
revision="b41c9d2e7f60";down_revision="a27d5c9e41f0";branch_labels=None;depends_on=None

def basecols():
    return [sa.Column("id",sa.UUID(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False)]

def upgrade():
    op.create_table("product_skus",sa.Column("product_id",sa.UUID(),nullable=False),sa.Column("code",sa.String(120),nullable=False),sa.Column("name",sa.String(160),nullable=False),sa.Column("billing_mode",sa.String(30),nullable=False),sa.Column("inventory_policy",sa.String(30),nullable=False,server_default="none"),sa.Column("is_active",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("is_sellable",sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column("metadata_json",postgresql.JSONB(),nullable=False,server_default=sa.text("'{}'::jsonb")),*basecols(),sa.ForeignKeyConstraint(["product_id"],["product_catalog_items.id"],ondelete="CASCADE"),sa.PrimaryKeyConstraint("id"),sa.UniqueConstraint("code"))
    op.create_table("regional_rates",sa.Column("sku_id",sa.UUID(),nullable=False),sa.Column("region_code",sa.String(16),nullable=False),sa.Column("currency",sa.String(3),nullable=False),sa.Column("billing_period",sa.String(20),nullable=False),sa.Column("metering_unit",sa.String(30),nullable=False),sa.Column("unit_price_minor",sa.BigInteger(),nullable=False),sa.Column("rate_kind",sa.String(30),nullable=False,server_default="catalog"),sa.Column("is_active",sa.Boolean(),nullable=False,server_default=sa.true()),*basecols(),sa.ForeignKeyConstraint(["sku_id"],["product_skus.id"],ondelete="CASCADE"),sa.PrimaryKeyConstraint("id"))
    op.create_table("billing_wallets",sa.Column("organization_id",sa.UUID(),nullable=False),sa.Column("user_id",sa.UUID(),nullable=True),sa.Column("currency",sa.String(3),nullable=False),sa.Column("wallet_type",sa.String(30),nullable=False,server_default="customer"),sa.Column("balance_minor",sa.BigInteger(),nullable=False,server_default="0"),sa.Column("auto_recharge_enabled",sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column("auto_recharge_threshold_minor",sa.BigInteger(),nullable=False,server_default="0"),sa.Column("auto_recharge_amount_minor",sa.BigInteger(),nullable=False,server_default="0"),sa.Column("low_balance_threshold_minor",sa.BigInteger(),nullable=False,server_default="0"),sa.Column("critical_balance_threshold_minor",sa.BigInteger(),nullable=False,server_default="0"),*basecols(),sa.ForeignKeyConstraint(["organization_id"],["organizations.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["user_id"],["users.id"],ondelete="SET NULL"),sa.PrimaryKeyConstraint("id"))
    op.create_table("wallet_ledger_entries",sa.Column("wallet_id",sa.UUID(),nullable=False),sa.Column("entry_type",sa.String(40),nullable=False),sa.Column("amount_minor",sa.BigInteger(),nullable=False),sa.Column("balance_after_minor",sa.BigInteger(),nullable=False),sa.Column("reference_type",sa.String(60),nullable=False,server_default=""),sa.Column("reference_id",sa.String(120),nullable=False,server_default=""),sa.Column("description",sa.String(255),nullable=False,server_default=""),sa.Column("metadata_json",postgresql.JSONB(),nullable=False,server_default=sa.text("'{}'::jsonb")),*basecols(),sa.ForeignKeyConstraint(["wallet_id"],["billing_wallets.id"],ondelete="RESTRICT"),sa.PrimaryKeyConstraint("id"))
    op.create_table("promotions",sa.Column("code",sa.String(80),nullable=False),sa.Column("name",sa.String(120),nullable=False),sa.Column("discount_type",sa.String(30),nullable=False),sa.Column("discount_value",sa.BigInteger(),nullable=False),sa.Column("region_code",sa.String(16),nullable=False,server_default="GLOBAL"),sa.Column("product_code",sa.String(120),nullable=False,server_default=""),sa.Column("stackable",sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column("max_redemptions",sa.Integer(),nullable=False,server_default="0"),sa.Column("starts_at",sa.DateTime(timezone=True),nullable=True),sa.Column("ends_at",sa.DateTime(timezone=True),nullable=True),sa.Column("is_active",sa.Boolean(),nullable=False,server_default=sa.true()),*basecols(),sa.PrimaryKeyConstraint("id"),sa.UniqueConstraint("code"))
    op.create_table("partner_accounts",sa.Column("organization_id",sa.UUID(),nullable=False),sa.Column("partner_type",sa.String(30),nullable=False),sa.Column("tier",sa.String(30),nullable=False,server_default="registered"),sa.Column("wholesale_discount_bps",sa.Integer(),nullable=False,server_default="0"),sa.Column("commission_bps",sa.Integer(),nullable=False,server_default="0"),sa.Column("settlement_currency",sa.String(3),nullable=False,server_default="PKR"),sa.Column("status",sa.String(30),nullable=False,server_default="pending"),*basecols(),sa.ForeignKeyConstraint(["organization_id"],["organizations.id"],ondelete="CASCADE"),sa.PrimaryKeyConstraint("id"))
    op.create_table("partner_earnings",sa.Column("partner_account_id",sa.UUID(),nullable=False),sa.Column("earning_type",sa.String(30),nullable=False),sa.Column("currency",sa.String(3),nullable=False),sa.Column("gross_minor",sa.BigInteger(),nullable=False),sa.Column("earning_minor",sa.BigInteger(),nullable=False),sa.Column("status",sa.String(30),nullable=False,server_default="pending"),sa.Column("available_at",sa.DateTime(timezone=True),nullable=True),sa.Column("paid_at",sa.DateTime(timezone=True),nullable=True),sa.Column("metadata_json",postgresql.JSONB(),nullable=False,server_default=sa.text("'{}'::jsonb")),*basecols(),sa.ForeignKeyConstraint(["partner_account_id"],["partner_accounts.id"],ondelete="RESTRICT"),sa.PrimaryKeyConstraint("id"))
    op.create_table("subscriptions",sa.Column("organization_id",sa.UUID(),nullable=False),sa.Column("user_id",sa.UUID(),nullable=False),sa.Column("sku_id",sa.UUID(),nullable=False),sa.Column("billing_period",sa.String(20),nullable=False),sa.Column("currency",sa.String(3),nullable=False),sa.Column("amount_minor",sa.BigInteger(),nullable=False),sa.Column("status",sa.String(30),nullable=False,server_default="active"),sa.Column("next_bill_at",sa.DateTime(timezone=True),nullable=True),sa.Column("auto_renew",sa.Boolean(),nullable=False,server_default=sa.true()),*basecols(),sa.ForeignKeyConstraint(["organization_id"],["organizations.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["user_id"],["users.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["sku_id"],["product_skus.id"],ondelete="RESTRICT"),sa.PrimaryKeyConstraint("id"))
    op.create_table("payment_method_tokens",sa.Column("organization_id",sa.UUID(),nullable=False),sa.Column("user_id",sa.UUID(),nullable=False),sa.Column("provider",sa.String(60),nullable=False),sa.Column("provider_token",sa.String(255),nullable=False),sa.Column("display_label",sa.String(120),nullable=False,server_default=""),sa.Column("status",sa.String(30),nullable=False,server_default="active"),*basecols(),sa.ForeignKeyConstraint(["organization_id"],["organizations.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["user_id"],["users.id"],ondelete="CASCADE"),sa.PrimaryKeyConstraint("id"))
    op.create_table("usage_sessions",sa.Column("organization_id",sa.UUID(),nullable=False),sa.Column("user_id",sa.UUID(),nullable=False),sa.Column("sku_id",sa.UUID(),nullable=False),sa.Column("wallet_id",sa.UUID(),nullable=False),sa.Column("provider_type",sa.String(30),nullable=False,server_default="khan_cloud"),sa.Column("provider_reference",sa.String(120),nullable=False,server_default=""),sa.Column("status",sa.String(30),nullable=False,server_default="running"),sa.Column("currency",sa.String(3),nullable=False),sa.Column("per_minute_price_minor",sa.BigInteger(),nullable=False),sa.Column("started_at",sa.DateTime(timezone=True),nullable=False),sa.Column("last_metered_at",sa.DateTime(timezone=True),nullable=True),sa.Column("stopped_at",sa.DateTime(timezone=True),nullable=True),sa.Column("stop_reason",sa.String(80),nullable=False,server_default=""),*basecols(),sa.ForeignKeyConstraint(["organization_id"],["organizations.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["user_id"],["users.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["sku_id"],["product_skus.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["wallet_id"],["billing_wallets.id"],ondelete="RESTRICT"),sa.PrimaryKeyConstraint("id"))
    op.create_table("usage_charges",sa.Column("usage_session_id",sa.UUID(),nullable=False),sa.Column("units",sa.Integer(),nullable=False),sa.Column("currency",sa.String(3),nullable=False),sa.Column("unit_price_minor",sa.BigInteger(),nullable=False),sa.Column("amount_minor",sa.BigInteger(),nullable=False),sa.Column("period_started_at",sa.DateTime(timezone=True),nullable=False),sa.Column("period_ended_at",sa.DateTime(timezone=True),nullable=False),*basecols(),sa.ForeignKeyConstraint(["usage_session_id"],["usage_sessions.id"],ondelete="CASCADE"),sa.PrimaryKeyConstraint("id"))
    op.create_table("host_capacity_offers",sa.Column("node_id",sa.UUID(),nullable=False),sa.Column("sku_id",sa.UUID(),nullable=False),sa.Column("provider_type",sa.String(30),nullable=False,server_default="marketplace_host"),sa.Column("currency",sa.String(3),nullable=False),sa.Column("minimum_payout_per_hour_minor",sa.BigInteger(),nullable=False,server_default="0"),sa.Column("khan_cloud_payout_per_hour_minor",sa.BigInteger(),nullable=False,server_default="0"),sa.Column("availability_state",sa.String(30),nullable=False,server_default="unavailable"),sa.Column("is_verified",sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column("metadata_json",postgresql.JSONB(),nullable=False,server_default=sa.text("'{}'::jsonb")),*basecols(),sa.ForeignKeyConstraint(["node_id"],["nodes.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["sku_id"],["product_skus.id"],ondelete="CASCADE"),sa.PrimaryKeyConstraint("id"))

    bind=op.get_bind()
    families=[("gpu-catalog","gpu_compute","GPU Catalog"),("gaming-catalog","gaming","Gaming Catalog"),("storage-catalog","storage","Storage Catalog"),("network-catalog","network","Network Catalog"),("webhosting-catalog","web_hosting","Web Hosting Catalog")]
    for code,workload,name in families:
        row=bind.execute(sa.text("SELECT id FROM product_catalog_items WHERE code=:c"),{"c":code}).scalar()
        if not row:
            row=str(uuid.uuid4());bind.execute(sa.text("INSERT INTO product_catalog_items (id,code,workload_type,name,description,currency,is_active,is_sellable,metadata_json,created_at,updated_at) VALUES (:id,:c,:w,:n,:d,'PKR',true,false,'{}'::jsonb,now(),now())"),{"id":row,"c":code,"w":workload,"n":name,"d":f"Khan Cloud {name}."})
    gpu_models=[("rtx-3080-10g","RTX 3080 10GB",10),("rtx-3090-24g","RTX 3090 24GB",24),("rtx-4090-24g","RTX 4090 24GB",24),("rtx-5070ti-16g","RTX 5070 Ti 16GB",16),("rtx-5080-16g","RTX 5080 16GB",16),("rtx-5090-32g","RTX 5090 32GB",32),("a6000-48g","RTX A6000 48GB",48),("l4-24g","NVIDIA L4 24GB",24),("l40s-48g","NVIDIA L40S 48GB",48),("a100-80g","NVIDIA A100 80GB",80),("h100-80g","NVIDIA H100 80GB",80),("h200-141g","NVIDIA H200 141GB",141),("b200-180g","NVIDIA B200 180GB",180)]
    gpu_product=bind.execute(sa.text("SELECT id FROM product_catalog_items WHERE code='gpu-catalog'" )).scalar(); gaming_product=bind.execute(sa.text("SELECT id FROM product_catalog_items WHERE code='gaming-catalog'" )).scalar(); network_product=bind.execute(sa.text("SELECT id FROM product_catalog_items WHERE code='network-catalog'" )).scalar()
    for code,name,vram in gpu_models:
        for prefix,pid,mode in (("gpu-ai",gpu_product,"metered"),("gpu-dedicated",gpu_product,"subscription"),("gaming",gaming_product,"metered")):
            sku=f"{prefix}-{code}"
            if not bind.execute(sa.text("SELECT 1 FROM product_skus WHERE code=:c"),{"c":sku}).first():
                bind.execute(sa.text("INSERT INTO product_skus (id,product_id,code,name,billing_mode,inventory_policy,is_active,is_sellable,metadata_json,created_at,updated_at) VALUES (:id,:pid,:c,:n,:m,'inventory',true,false,CAST(:meta AS jsonb),now(),now())"),{"id":str(uuid.uuid4()),"pid":pid,"c":sku,"n":f"{name} {prefix}","m":mode,"meta":json.dumps({"gpu":name,"vram_gib":vram,"hourly_quoted_per_minute_charged":mode=="metered","periods":["daily","monthly","yearly"] if mode=="subscription" else []})})
    if not bind.execute(sa.text("SELECT 1 FROM product_skus WHERE code='dedicated-ipv4'" )).first():
        sid=str(uuid.uuid4());bind.execute(sa.text("INSERT INTO product_skus (id,product_id,code,name,billing_mode,inventory_policy,is_active,is_sellable,metadata_json,created_at,updated_at) VALUES (:id,:pid,'dedicated-ipv4','Dedicated Public IPv4','subscription','inventory',true,false,'{}'::jsonb,now(),now())"),{"id":sid,"pid":network_product});bind.execute(sa.text("INSERT INTO regional_rates (id,sku_id,region_code,currency,billing_period,metering_unit,unit_price_minor,rate_kind,is_active,created_at,updated_at) VALUES (:id,:sid,'PK','PKR','monthly','subscription',50000,'catalog',false,now(),now())"),{"id":str(uuid.uuid4()),"sid":sid})

def downgrade():
    for t in ("host_capacity_offers","usage_charges","usage_sessions","payment_method_tokens","subscriptions","partner_earnings","partner_accounts","promotions","wallet_ledger_entries","billing_wallets","regional_rates","product_skus"): op.drop_table(t)
