"""payment provider adapter v1

Revision ID: f2a002b10001
Revises: f1a001b10003
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = "f2a002b10001"
down_revision = "f1a001b10003"
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "payment_providers",
        sa.Column(
            "code",
            sa.String(length=60),
            nullable=False,
        ),
        sa.Column(
            "display_name",
            sa.String(length=120),
            nullable=False,
        ),
        sa.Column(
            "adapter_type",
            sa.String(length=80),
            nullable=False,
        ),
        sa.Column(
            "enabled",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "environment",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "capabilities_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "supported_currencies_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "credential_reference",
            sa.String(length=240),
            nullable=False,
        ),
        sa.Column(
            "webhook_secret_reference",
            sa.String(length=240),
            nullable=False,
        ),
        sa.Column(
            "webhook_tolerance_seconds",
            sa.BigInteger(),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=30),
            nullable=False,
        ),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            "webhook_tolerance_seconds > 0",
            name="ck_payment_provider_webhook_tolerance_positive",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )

    op.create_index(
        op.f("ix_payment_providers_code"),
        "payment_providers",
        ["code"],
        unique=True,
    )
    op.create_index(
        op.f("ix_payment_providers_status"),
        "payment_providers",
        ["status"],
        unique=False,
    )

    op.create_table(
        "payment_provider_references",
        sa.Column(
            "provider_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "reference_type",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "provider_reference",
            sa.String(length=180),
            nullable=False,
        ),
        sa.Column(
            "internal_resource_type",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "internal_resource_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "metadata_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["payment_providers.id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider_id",
            "reference_type",
            "provider_reference",
            name="uq_payment_provider_external_reference",
        ),
    )

    op.create_index(
        op.f("ix_payment_provider_references_provider_id"),
        "payment_provider_references",
        ["provider_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_provider_references_internal_resource_id"),
        "payment_provider_references",
        ["internal_resource_id"],
        unique=False,
    )
    op.create_index(
        "ix_payment_provider_internal_reference",
        "payment_provider_references",
        ["internal_resource_type", "internal_resource_id"],
        unique=False,
    )

    op.create_table(
        "payment_webhook_receipts",
        sa.Column(
            "provider_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "event_id",
            sa.String(length=180),
            nullable=False,
        ),
        sa.Column(
            "event_type",
            sa.String(length=80),
            nullable=False,
        ),
        sa.Column(
            "raw_body_sha256",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "normalized_payload_sha256",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "provider_timestamp",
            sa.BigInteger(),
            nullable=False,
        ),
        sa.Column(
            "signature_verified",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "processing_status",
            sa.String(length=30),
            nullable=False,
        ),
        sa.Column(
            "reconciliation_event_id",
            postgresql.UUID(as_uuid=True),
            nullable=True,
        ),
        sa.Column(
            "result_resource_type",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "result_resource_id",
            postgresql.UUID(as_uuid=True),
            nullable=True,
        ),
        sa.Column(
            "error_code",
            sa.String(length=80),
            nullable=False,
        ),
        sa.Column(
            "metadata_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            "provider_timestamp > 0",
            name="ck_payment_webhook_timestamp_positive",
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["payment_providers.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reconciliation_event_id"],
            ["payment_reconciliation_events.id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider_id",
            "event_id",
            name="uq_payment_webhook_provider_event",
        ),
    )

    op.create_index(
        op.f("ix_payment_webhook_receipts_provider_id"),
        "payment_webhook_receipts",
        ["provider_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_webhook_receipts_event_type"),
        "payment_webhook_receipts",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_webhook_receipts_processing_status"),
        "payment_webhook_receipts",
        ["processing_status"],
        unique=False,
    )


def downgrade():
    op.drop_index(
        op.f("ix_payment_webhook_receipts_processing_status"),
        table_name="payment_webhook_receipts",
    )
    op.drop_index(
        op.f("ix_payment_webhook_receipts_event_type"),
        table_name="payment_webhook_receipts",
    )
    op.drop_index(
        op.f("ix_payment_webhook_receipts_provider_id"),
        table_name="payment_webhook_receipts",
    )
    op.drop_table("payment_webhook_receipts")

    op.drop_index(
        "ix_payment_provider_internal_reference",
        table_name="payment_provider_references",
    )
    op.drop_index(
        op.f("ix_payment_provider_references_internal_resource_id"),
        table_name="payment_provider_references",
    )
    op.drop_index(
        op.f("ix_payment_provider_references_provider_id"),
        table_name="payment_provider_references",
    )
    op.drop_table("payment_provider_references")

    op.drop_index(
        op.f("ix_payment_providers_status"),
        table_name="payment_providers",
    )
    op.drop_index(
        op.f("ix_payment_providers_code"),
        table_name="payment_providers",
    )
    op.drop_table("payment_providers")
